### ISSUE TITLE
Bug: Car in core need fix.

### ISSUE THREAD

**Issue by urvishp80** [ericyuxuanye/Environment-Framework#95]
Getting error in the `car.py` in the core.

```
rays:list[float] = [],           
TypeError: 'type' object is not subscriptable
```

**Comment by haichencheng** [comment]
where did you see the error? it works fine in my environment. did you setup your environment following readme?

**Comment by urvishp80** [comment]
```
Traceback (most recent call last):
  File "D:/study_projects/UpWork/QuantumLabs/Environment-Framework/runner/runner.py", line 6, in <module>
    from racecar.model import load_model
  File "D:\study_projects\UpWork\QuantumLabs\Environment-Framework\runner\racecar\model.py", line 12, in <module>
    from core.src import model, car
  File "D:\study_projects\UpWork\QuantumLabs\Environment-Framework\core\src\model.py", line 2, in <module>
    from . import car
  File "D:\study_projects\UpWork\QuantumLabs\Environment-Framework\core\src\car.py", line 76, in <module>
    class TrackState:
  File "D:\study_projects\UpWork\QuantumLabs\Environment-Framework\core\src\car.py", line 80, in TrackState
    rays:list[float] = [],           
TypeError: 'type' object is not subscriptable

Process finished with exit code 1
``` 
This is full traceback. I just ran the `runner.py` and `ui.py`. For setup, I created a new virtual env with the libraries listed in the `requirements` file. Let me know if you need more info from my end. But as good practice using `float` to index the `list` is not good idea to begin with.

**Comment by urvishp80** [comment]
Solved after configuring the env properly
